### ISSUE TITLE
Secret scanner workflow fails to checkout code when PR is from fork

### ISSUE THREAD

**Issue by timfish** [getsentry/.github#131]
I'm guessing the issue is caused by the fork but I'm honestly not sure why it's failing here!

https://github.com/getsentry/sentry-electron/actions/runs/9793261370/job/27040829361?pr=937#step:3:61

**Comment by markstory** [comment]
cc @getsentry/security

**Comment by geoffg-sentry** [comment]
@timfish Odd one. It was the fetch that was failing on repeat:
`git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=3 origin +refs/heads/feat/update-sdks*:refs/remotes/origin/feat/update-sdks* +refs/tags/feat/update-sdks*:refs/tags/feat/update-sdks*`

Which itself was fine since it was properly referencing the refs from your fork. I re-ran the job and it passed without issue and that fetch returned as expected:
`  From https://github.com/getsentry/sentry-electron
   * [new branch]      feat/update-sdks -> origin/feat/update-sdk`
   
  Your guess is as good as mine here.

**Comment by Jeffreyhung** [comment]
The fetch depth was removed in the workflow, which should resolve any issues coming from a fork
https://github.com/getsentry/.github/pull/132
